"""Add sessions, price_tiers, map_url to shows

Revision ID: a3f3702ead26
Revises: 067c41fcb5fb
Create Date: 2025-06-15 12:35:41.007140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f3702ead26'
down_revision = '067c41fcb5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('sessions', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('shows', sa.Column('price_tiers', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('shows', sa.Column('map_url', sa.String(length=256), nullable=False, server_default=''))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_column('map_url')
        batch_op.drop_column('price_tiers')
        batch_op.drop_column('sessions')

    # ### end Alembic commands ###
