"""Add user profile fields

Revision ID: a6eb9c2aa5e6
Revises: e12912287830
Create Date: 2025-06-13 14:04:23.017893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6eb9c2aa5e6'
down_revision = 'e12912287830'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('users', sa.Column('realname', sa.String(length=64), nullable=False, server_default=""))
    op.add_column('users', sa.Column('gender', sa.String(length=8), nullable=False, server_default="保密"))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=False, server_default="1970-01-01"))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=False, server_default=""))
    op.add_column('users', sa.Column('province', sa.String(length=32), nullable=False, server_default=""))
    op.add_column('users', sa.Column('city', sa.String(length=32), nullable=False, server_default=""))
    op.add_column('users', sa.Column('district', sa.String(length=32), nullable=False, server_default=""))
    op.add_column('users', sa.Column('address', sa.String(length=128), nullable=False, server_default=""))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
